trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRepository: "nishants/oapi-service"
  tag: "v1.0.$(Build.BuildId)"
  imageName: "nishants/oapi-service:v1.0.$(Build.BuildId)"
  buildConfiguration: 'Release'

steps:
- task: Docker@2
  displayName: Build Image
  inputs:
    command: build
    dockerfile: '**/Dockerfile'
    repository: $(dockerRepository)          
    tags: $(tag)          

- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: DockerHubServiceConnection

- task: Docker@2
  displayName: Publish Image
  inputs:
    command: push
    containerRegistry: DockerHubServiceConnection
    repository: $(dockerRepository)          
    tags: $(tag)  
