apiVersion : apps/v1
kind: Deployment
metadata:
  name: oapiserviceone 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oapiserviceone
  template:
    metadata:
      labels:
        app: oapiserviceone 
    spec:
      containers:
        - name: oapiserviceone 
          image: saxolab.azurecr.io/oapiserviceone
          ports:
          - containerPort: 80