# Create pods that runs our docker image
apiVersion : apps/v1
kind: Deployment
metadata:
  name: oapiserviceone 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oapiserviceone
  template:
    metadata:
      labels:
        app: oapiserviceone 
    spec:
      containers:
        - name: oapiserviceone 
          image: saxolab.azurecr.io/oapiserviceone # Image name
          ports:
          - containerPort: 80