# Create a load balancer pod that receives traffic from
# internet and load-balances to our pods
apiVersion: v1
kind: Service
metadata:
    name: oapiserviceone
spec:
    type: LoadBalancer
    ports:
    - port: 80    # The port our container(in pods) listens to
    selector:
        app: oapiserviceone