# This part creates a pod that runs our docker image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oapi-app-deployment
spec:
  replicas: 2    # Alwasy run two isntances of app
  selector:
    matchLabels:
      app: oapi-app
  template:
    metadata:
      labels:
        app: oapi-app
    spec:
      containers:
        - name: oapi-app
          image: nishants/oapi-service:v1.0 # Dockerhub image
          ports:
            - containerPort: 80         # Port that our app listens to
          imagePullPolicy: Always       # To keep simple for now